---
title: "Data_Import"
format: html
editor: visual
---

```{r}
dta_pib <- read.csv("https://sdmx.oecd.org/public/rest/data/OECD.SDD.NAD,DSD_NAAG@DF_NAAG_I,1.0/A.ZAF+BRA+CHN+IND+IDN+RUS+AUS+AUT+BEL+CAN+CHL+COL+CRI+CZE+DNK+EST+FIN+FRA+DEU+GRC+HUN+ISL+IRL+ISR+ITA+JPN+KOR+LVA+LTU+LUX+MEX+NLD+NZL+NOR+POL+PRT+SVK+SVN+ESP+SWE+CHE+TUR+GBR+USA.B1GQ.USD_PPP.?startPeriod=2015&dimensionAtObservation=AllDimensions&format=csvfilewithlabels")
```

```{r}
dta_pib_hab <- read.csv("https://sdmx.oecd.org/public/rest/data/OECD.SDD.NAD,DSD_NAAG@DF_NAAG_I,1.0/A.ZAF+BRA+CHN+IND+IDN+RUS+AUS+AUT+BEL+CAN+CHL+COL+CRI+CZE+DNK+EST+FIN+FRA+DEU+GRC+HUN+ISL+IRL+ISR+ITA+JPN+KOR+LVA+LTU+LUX+MEX+NLD+NZL+NOR+POL+PRT+SVK+SVN+ESP+SWE+CHE+TUR+GBR+USA.B1GQ_POP.USD_PPP_PS.?startPeriod=2015&dimensionAtObservation=AllDimensions&format=csvfilewithlabels")
```

```{r}
dta_pib_sante <- read.csv("https://sdmx.oecd.org/public/rest/data/OECD.ELS.HD,DSD_SHA%40DF_SHA,1.0/DEU+AUS+AUT+BEL+CAN+CHL+COL+KOR+CRI+DNK+ESP+EST+USA+FIN+FRA+GRC+HUN+IRL+ISL+ISR+ITA+JPN+LVA+LTU+LUX+MEX+NOR+NZL+NLD+POL+PRT+SVK+GBR+SVN+SWE+CHE+CZE+TUR+ZAF+ARG+BRA+BGR+CHN+CYP+HRV+IND+IDN+MLT+PER+ROU+THA+UKR.A.EXP_HEALTH.PT_B1GQ..._T._T._T...?startPeriod=2015&dimensionAtObservation=AllDimensions&format=csvfilewithlabels")
```

```{r}
dta_medicament <- read.csv("https://sdmx.oecd.org/public/rest/data/OECD.ELS.HD,HEALTH_PHMC@DF_PHMC_CONSUM,1.1/DEU+AUS+AUT+BEL+CAN+CHL+KOR+CRI+DNK+ESP+EST+FIN+FRA+GRC+HUN+IRL+ISL+ISR+ITA+LVA+LTU+LUX+NOR+NZL+NLD+POL+PRT+SVK+GBR+SVN+SWE+CZE+TUR+BGR+HRV+PER+ROU....J?startPeriod=2015&dimensionAtObservation=AllDimensions&format=csvfilewithlabels")
```

```{r}
dta_air_quality <- read.csv("https://sdmx.oecd.org/public/rest/data/OECD.ENV.EPI,DSD_AIR_POL@DF_AIR_POLL,1.0/AUT+AUS+BEL+CAN+CHL+COL+CRI+CZE+DNK+EST+FIN+FRA+DEU+GRC+HUN+ISL+IRL+ISR+ITA+JPN+LVA+LTU+LUX+MEX+NLD+NZL+NOR+POL+PRT+SVK+SVN+ESP+SWE+CHE+TUR+GBR+USA.A.POP_EXP_POL+MEAN_POP.EL_GT_10..PT_POP.?startPeriod=2011&dimensionAtObservation=AllDimensions&format=csvfilewithlabels")
```

```{r}
dta_mortalite_evitable <- read.csv("https://sdmx.oecd.org/public/rest/data/OECD.ELS.HD,DSD_HEALTH_STAT@DF_AM,1.0/all?dimensionAtObservation=AllDimensions&format=csvfilewithlabels")
```

```{r}
dta_RH_sante <- read.csv("https://sdmx.oecd.org/public/rest/data/OECD.ELS.HD,DSD_HEALTH_EMP_REAC@DF_REAC,1.0/all?dimensionAtObservation=AllDimensions&format=csvfilewithlabels")
```

```{r}
dta_qualite_soins <-read.csv("https://sdmx.oecd.org/public/rest/data/OECD.ELS.HD,DSD_HCQO@DF_HCQO,1.1/all?dimensionAtObservation=AllDimensions&format=csvfilewithlabels")
```

```{r}
dta_agri <- read.csv("https://sdmx.oecd.org/public/rest/data/OECD.TAD.ARP,DSD_AGRI_ENV@DF_AEI,1.0/AUS+AUT+BEL+CAN+CHL+COL+CRI+CZE+DNK+EST+FIN+FRA+DEU+GRC+HUN+ISL+IRL+ISR+ITA+JPN+KOR+LVA+LTU+LUX+MEX+NLD+NZL+NOR+POL+PRT+SVK+SVN+ESP+SWE+CHE+TUR+GBR+USA+EU+ARG+BRA+BGR+CHN+HRV+CYP+IND+IDN+KAZ+MLT+PHL+ROU+RUS+ZAF+UKR+VNM.A.WATER+I_AREA+W_QUALITY+BIODIV+DRINK_W+GHG_AG+O_F+NRJ+IPP+AGR+WASTE+OTH+TOTGHG_SOURCE+TOTPEST+TOTFRESHW+IRRIGATIONAREA+BIRDS+I0+MONITSITESN+MONITSITEP+MONITSITEPEST+CH4AGR+CO2AGR+N2OAGR+TOTAGR_LAND._Z._Z._Z.HA+KG+T+T_CO2E+TOE+PT_ALAR+PT_EM_NO3+PT_EM_PO4+PT_MNTR_STS+IX+M3?startPeriod=2014&dimensionAtObservation=AllDimensions&format=csvfilewithlabels")
```



```{r}
dta_Financement_sante_full <-read.csv("../Data/RAw_Financement_health.csv")
```






```{r}

# Mettre toutes les données dans une 
datalist <- list(
  dta_health = dta_health,
  dta_pib = dta_pib,
  dta_pib_hab = dta_pib_hab,
  dta_pib_sante = dta_pib_sante,
  dta_medicament = dta_medicament,
  dta_air_quality = dta_air_quality,
  dta_mortalite_evitable = dta_mortalite_evitable,
  dta_qualite_soins = dta_qualite_soins,
  dta_agri = dta_agri,
  dta_RH_sante = dta_RH_sante,
  dta_Financement_sante_full = dta_Financement_sante_full

)

# Sauvegarde en boucle
for(n in names(datalist)){
  saveRDS(datalist[[n]], file = paste0("../data/", n, ".rds"))
}


```
