---
title: "data_cleaning"
format: html
editor: visual
---


```{r}
dta_health <- readRDS("../data/dta_health.rds")
dta_pib <- readRDS("../data/dta_pib.rds")
dta_pib_hab <- readRDS("../data/dta_pib_hab.rds")
dta_pib_sante <- readRDS("../data/dta_pib_sante.rds")
dta_medicament <- readRDS("../data/dta_medicament.rds")
dta_air_quality <- readRDS("../data/dta_air_quality.rds")
dta_mortalite_evitable <- readRDS("../data/dta_mortalite_evitable.rds")
dta_RH_sante <- readRDS("../data/dta_RH_sante.rds")
dta_qualite_soins <- readRDS("../data/dta_qualite_soins.rds")
dta_agri <- readRDS("../data/dta_agri.rds")
dta_finance <- read.csv("../data/Raw_Financement_health.csv")

```



```{r}
table(dta_medicament$Measure)
```


```{r}
library(data.table)
dta_health <- as.data.table(dta_health)
dta_pib <- data.table(dta_pib)
dta_pib_hab <- data.table(dta_pib_hab)
dta_pib_sante <- data.table(dta_pib_sante)
dta_air_quality <- data.table(dta_air_quality)
dta_medicament <- data.table(dta_medicament)
dta_qualite_soins <- data.table(dta_qualite_soins)
dta_mortalite_evitable <- data.table(dta_mortalite_evitable)
dta_RH_sante <- data.table(dta_RH_sante)
dta_qualite_soins <- data.table(dta_qualite_soins)
dta_agri <- data.table(dta_agri)
dta_finance <- data.table(dta_finance)
```
```{r}
dta_mortalite_evitable <- readRDS("../data/dta_mortalite_evitable.rds")
table(dta_mortalite_evitable$Measure)
```


```{r}
dta_finance
```


```{r}
table(dta_RH_sante$Health.profession, dta_RH_sante$Unit.of.measure)
```

Cleaning des données

```{r}
dta_health <- dta_health[,.(REF_AREA,Reference.area,Measure,TIME_PERIOD,OBS_VALUE,Unit.of.measure)]
dta_health <- dta_health[, Tableau := "Health"]

dta_pib <- dta_pib[,.(REF_AREA,Reference.area,Measure,TIME_PERIOD,OBS_VALUE,Unit.of.measure)]
dta_pib <- dta_pib[, Tableau := "PIB"]

dta_pib_hab <- dta_pib_hab[,.(REF_AREA,Reference.area,Measure,TIME_PERIOD,OBS_VALUE,Unit.of.measure)]
dta_pib_hab <- dta_pib_hab[, Tableau := "PIB par Habitant"]

dta_pib_sante <- dta_pib_sante[,.(REF_AREA,Reference.area,Measure,TIME_PERIOD,Unit.of.measure,OBS_VALUE)]
dta_pib_sante <- dta_pib_sante[, Tableau := "PIB_sante"]

dta_air_quality <- dta_air_quality[,.(REF_AREA,Reference.area,Measure,TIME_PERIOD,Unit.of.measure,OBS_VALUE)]
dta_air_quality <- dta_air_quality[, Tableau := "Exposition_pollution"]

dta_qualite_soins <- dta_qualite_soins[,.(REF_AREA,Reference.area,Measure,TIME_PERIOD,Unit.of.measure,OBS_VALUE)]
dta_qualite_soins <- dta_qualite_soins[, Tableau := "Qualite_des_soins"]

dta_medicament <- dta_medicament[,.(REF_AREA,Reference.area,Measure,TIME_PERIOD,Unit.of.measure,OBS_VALUE)]
dta_medicament <- dta_medicament[, Tableau := "Medicament"]

dta_mortalite_evitable <- dta_mortalite_evitable[,.(REF_AREA,Reference.area,Measure,TIME_PERIOD,Unit.of.measure,OBS_VALUE)]
dta_mortalite_evitable <- dta_mortalite_evitable[, Tableau := "Mortalite_evitable"]
```

```{r}
dta_mortalite_evitable
```


```{r}
dta_mortalite_evitable[Reference.area=="Bulgaria" & TIME_PERIOD == 2017 & Measure == "treatable_mortality"]
```



```{r}
dta_agri <- dta_agri[,.(REF_AREA,Reference.area,Measure,TIME_PERIOD,Unit.of.measure,OBS_VALUE)]
dta_agri <- dta_agri[, Tableau := "Agriculture"]


dta_RH_sante <- dta_RH_sante[,.(REF_AREA,Reference.area,Measure,TIME_PERIOD,Unit.of.measure,OBS_VALUE,Health.profession)]
dta_RH_sante <- dta_RH_sante[, Tableau := "Ressources_Sante"]

dta_finance$Unit.of.measure <-  dta_finance$Unité.de.mesure
dta_finance$Measure <-  dta_finance$Mesure
dta_finance$Reference.area <-  dta_finance$Zone.de.référence


dta_finance <- dta_finance[,.(REF_AREA,Reference.area,Measure,TIME_PERIOD,Unit.of.measure,OBS_VALUE,Fournisseur.de.soins.de.santé,Fonction.de.santé,Mode.de.prestation)]
dta_finance <- dta_finance[, Tableau := "Ressources_Financiere_Sante"]
```

Création du tableau final

```{r}
datalist <- list(
  dta_health = dta_health,
  dta_pib = dta_pib,
  dta_pib_hab = dta_pib_hab,
  dta_pib_sante = dta_pib_sante,
  dta_medicament = dta_medicament,
  dta_air_quality = dta_air_quality,
  dta_mortalite_evitable = dta_mortalite_evitable,
  dta_qualite_soins = dta_qualite_soins,
  dta_agri = dta_agri,
  dta_RH_sante = dta_RH_sante,
  dta_finance = dta_finance
)

data <- rbindlist(datalist, use.names=TRUE, fill=TRUE)

```

# Nettoyage de "Measure"
```{r}
library(stringi)

# 1. Mettre en minuscules
data[, Measure := tolower(Measure)]

# 2. Supprimer les accents
data[, Measure := stri_trans_general(Measure, "Latin-ASCII")]

# 3. Supprimer les caractères spéciaux sauf alphanumériques et espaces
data[, Measure := gsub("[^a-z0-9 ]", "", Measure)]

# 4. Remplacer les espaces par des underscores
data[, Measure := gsub(" +", "_", Measure)]
```

# Nettoyage de Unit.of.measure

```{r}

# 1. Mettre en minuscules
data[, Unit.of.measure := tolower(Unit.of.measure)]

# 2. Supprimer les accents
data[, Unit.of.measure := stri_trans_general(Unit.of.measure, "Latin-ASCII")]

# 3. Supprimer les caractères spéciaux sauf alphanumériques et espaces
data[, Unit.of.measure := gsub("[^a-z0-9 ]", "", Unit.of.measure)]

# 4. Remplacer les espaces par des underscores
data[, Unit.of.measure := gsub(" +", "_", Unit.of.measure)]
```



```{r}
dt[, lapply(.SD, FUN = as.factor) , by = c("OBS_VALUE","TIME_PERIOD")]
```

```{r}
save(data, file = "../data/data_cleaned.RData")

```



```{r}
data
```

